---
abstract: 'distribute points aesthetically in R^n'
author:
  - 'Max Maischein <corion@cpan.org>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.66, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Random-PoissonDisc
no_index:
  directory:
    - t
    - inc
requires:
  List::Util: 0
  Math::Random::MT::Auto: 0
  perl: 5.006
resources:
  repository: http://github.com/Corion/random-poissondisc
version: 0.02
