--- #YAML:1.0
name:               Random-PoissonDisc
version:            0.01
abstract:           distribute points aesthetically in R^n
author:
    - Max Maischein <corion@cpan.org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    List::Util:           0
    Math::Random::MT::Auto:  0
    perl:                 5.006
resources:
    repository:  http://github.com/Corion/random-poissondisc
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.50
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
